theme: jekyll-theme-hacker
# ------------------------------------------------------------------------------
# Custom settings
# ------------------------------------------------------------------------------
#blog pagination settings
paginate: 5
paginate_path: "/blog/page:num/"
# timezone 
timezone: Europe/Bucharest
